on:
  push:
  workflow_dispatch:


jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: devcontainers/ci@v0.3
        with:
          imageName: test
          push: never
          runCmd: exit 123

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: devcontainers/ci@v0.3
        with:
          imageName: test
          push: never
          runCmd: |
            exit 123

  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: devcontainers/ci@v0.3
        with:
          imageName: test
          push: never
          runCmd: |
            set -e
            exit 123
